"""removed nullable=false temporarily




Revision ID: 37bea8a35788
Revises: 446595784901
Create Date: 2016-05-15 23:56:46.365428

"""

# revision identifiers, used by Alembic.
revision = '37bea8a35788'
down_revision = '446595784901'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('register', 'address',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('register', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('register', 'email',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('register', 'mobile',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('register', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('register', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('register', 'mobile',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('register', 'email',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('register', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('register', 'address',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    ### end Alembic commands ###
