"""initial migration

Revision ID: 446595784901
Revises: None
Create Date: 2016-05-15 16:14:31.458643

"""

# revision identifiers, used by Alembic.
revision = '446595784901'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('cardetail', sa.String(length=15), nullable=True),
    sa.Column('license_detail', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('loginid', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('referalid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referalid'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('loginid'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('liftavailable',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('startlocation', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('seatavailable', sa.Integer(), nullable=False),
    sa.Column('totalseats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('liftrequired',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('startlocation', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('travelrecord',
    sa.Column('travel_id', sa.Integer(), nullable=False),
    sa.Column('ownerid', sa.Integer(), nullable=True),
    sa.Column('passengerid', sa.Integer(), nullable=True),
    sa.Column('distancetravelled', sa.Float(), nullable=False),
    sa.Column('g_pointsearnedbyowner', sa.Integer(), nullable=False),
    sa.Column('g_pointsusedbypassenger', sa.Integer(), nullable=False),
    sa.Column('refralpoints', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownerid'], ['register.id'], ),
    sa.ForeignKeyConstraint(['passengerid'], ['register.id'], ),
    sa.PrimaryKeyConstraint('travel_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travelrecord')
    op.drop_table('liftrequired')
    op.drop_table('liftavailable')
    op.drop_table('register')
    ### end Alembic commands ###
